import "./globals.css";

import { Roboto } from "next/font/google";
import * as React from "react";

import Footer from "../components/footer";
import Navbar from "../components/navbar";
import ThemeRegistry from "./ThemeRegistry";

import type { Metadata } from "next";
const roboto = Roboto({ weight: ["300", "400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`min-h-screen ${roboto.className}`}>
        <ThemeRegistry options={{ key: "mui" }}>
          <Navbar />
          {children}
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  );
}
