import "./globals.css";
import { Roboto } from "next/font/google";
const roboto = Roboto({ subsets: ["latin"], weight: "400" });

import MenuBar from "@/components/MenuBar";

export const metadata = {
  title: "jay's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <MenuBar />
        {children}
        </body>
    </html>
  );
}
